### ISSUE TITLE
关于小米漫游支持

### ISSUE THREAD

**Issue by etnperlong** [linusyang92/mipay-extract#12]
亲爱的开发者大大您好
我是小米Note顶配的用户，官方已停更，最新版本为MIUI9开发版7.11.21，Android 7.0 based
打算刷回MIUI养老😂于是使用您的脚本提取国内ROM功能
修改了您的脚本，**增加小米漫游APP(/priv-app/VirtualSim/VirtualSim.apk)**
并且使用Magisk 17000 template 刷入
但是发现刷入之后，**小米漫游APP会自动冻结**
使用系统设置启用以及钛备份解冻均无效果
搜遍网络上只有恢复小米支付，但无恢复小米漫游的教程

以下是我开机后第一时间用MatLog抓的log，希望作者能帮帮忙，谢谢！
[2018-09-04-16-59-11.txt](https://github.com/linusyang92/mipay-extract/files/2347940/2018-09-04-16-59-11.txt)
[device_info.txt](https://github.com/linusyang92/mipay-extract/files/2347941/device_info.txt)

**Comment by linusyang92** [comment]
Unfortunately, the Miui itself forbids the roaming service to work in the international version. The package will be automatically disabled. You need to revese-engineer the service.jar and patch out the code that does this. Only extracting and installing the apk does not work.

**Comment by etnperlong** [comment]
Thank you! I will try to solve this problem.
