### ISSUE TITLE
Doesn't support P image

### ISSUE THREAD

**Issue by EraserKing** [linusyang92/mipay-extract#14]
MIX 2S MIUI 10 8.9.7 (http://bigota.d.miui.com/8.9.7/miui_MIMIX2S_8.9.7_549955dacb_9.0.zip) is based on Android P, but this tool cannot support extracting wallet related files.

The system image has both vdex and odex files, and firstly it fails on deodex.
![image](https://user-images.githubusercontent.com/1160403/45285228-41f02d00-b515-11e8-975d-e51d61ebb68e.png)

The vdex file cannot be deodexed. I had a research and found this is caused by out-of-date vdexextractor. The author claimed to support Android P in new version and I compiled a new version which indeed works.
[vdexExtractor.zip](https://github.com/linusyang92/mipay-extract/files/2365777/vdexExtractor.zip)

But later it fails on a "mv" command (extract.sh, line 136).
![image](https://user-images.githubusercontent.com/1160403/45285373-9c898900-b515-11e8-8da3-fd39d36bdcca.png)

I don't know why this is happening and I checked, the folder originally has Mipay.odex and Mipay.vdex , and after vdexextractor a new Mipay_classes.cdex is created, but I have no idea of what is going to be fixed here. Thanks.

**Comment by EraserKing** [comment]
Seems the vdexExtractor compiled by me is still somehow wrong. It doesn't output file into proper location as the bash script desires.

**Comment by linusyang** [comment]
@EraserKing Try the latest version to see if it works. No Windows support yet.

**Comment by EraserKing** [comment]
Thanks. The extraction works but after I flash it, there's no Mi Wallet app in system. Not sure about the reason.
And due to some other reasons I have to revert to Oreo builds, so I would like to have this issue opened until Pie issues are solved and I would try this again, if you don't mind.

**Comment by EraserKing** [comment]
It's working with MIUI EU build. Seems a problem with AppVault parameter but I would like to leave it a separate issue. Thanks.

**Comment by linusyang** [comment]
@EraserKing Thanks for reporting! I have added Windows support in the latest commit.
I have tried with http://bigota.d.miui.com/8.9.7/miui_MIMIX2S_8.9.7_549955dacb_9.0.zip using `--appvault` flag. The package can be patched correctly. The issue may be related to #13 ([post](https://github.com/linusyang92/mipay-extract/issues/13#issuecomment-419754722)).
