### ISSUE TITLE
能否一并提取主题商店呢?

### ISSUE THREAD

**Issue by PowerDi** [linusyang92/mipay-extract#15]
对于我来说，实在能力有限去获取新的更新，能否也把主题商店也一起提取呢？国内的主题商店还是比较好用。信息助手确实有点问题，国际版的包名不一样之后，一些功能异常。谢谢你的工作给我们带来了那么大的便利性！

**Comment by shunf4** [comment]
You can try this [Node.JS app](https://github.com/shunf4/ZhutiSpoof). It can download MIUI themes of various UI versions from Chinese market. Downloaded .mtz packages can be directly imported into global miui theme manager.

Just run `node app.js` and access `localhost:4000`. Hope it helps :)

**Comment by linusyang** [comment]
@tengxunbc The mechanism of AppVault may have changed in the latest MIUI.  Maybe we need to modify the apk's identifier. I am still using MIUI 9 stable and doesn't have a proper device to test. You can experiment on your own if you are experienced with Android and MIUI.

There is no plan to support extracting other apps. Even if you extract the theme.apk from China version, the app itself will not use the China store in the global/eu version because of system limitations. Also, It is not appropriate to modify the theme.apk since there are potential copyright issues.

**Comment by tengxunbc** [comment]
> You can try this [Node.JS app](https://github.com/shunf4/ZhutiSpoof). It can download MIUI themes of various UI versions from Chinese market. Downloaded .mtz packages can be directly imported into global miui theme manager.
> 
> Just run `node app.js` and access `localhost:4000`. Hope it helps :)

Thanks a lot. I think it would be helpful for me.

**Comment by tengxunbc** [comment]
> @tengxunbc The mechanism of AppVault may have changed in the latest MIUI (see also #13). Maybe we need to modify the apk's identifier. I am still using MIUI 9 stable and doesn't have a proper device to test. You can experiment on your own if you are experienced with Android and MIUI.
> 
> There is no plan to support extracting other apps. Even if you extract the theme.apk from China version, the app itself will not use the China store in the global/eu version because of system limitations. Also, It is not appropriate to modify the theme.apk since there are potential copyright issues.

Copy that. Why don't u update ur version to MIUI10 since it have changed a lot. Many features are changed and we need ur further research.

**Comment by linusyang** [comment]
@tengxunbc MIUI 10 is way too buggy for me. Settings and Security Center apps randomly eat a lot of CPU (process names are `com.android.settings:remote` and `com.miui.securitycenter:remote`). Android System is always the most battery consuming app on my phone. Personally, I don't need any new features of MIUI 10. I may stick to MIUI 9 for a while until it is stable enough.

**Comment by tengxunbc** [comment]
> @tengxunbc MIUI 10 is way too buggy for me. Settings and Security Center apps randomly eat a lot of CPU (process names are `com.android.settings:remote` and `com.miui.securitycenter:remote`). Android System is always the most battery consuming app on my phone. Personally, I don't need any new features of MIUI 10. I may stick to MIUI 9 for a while until it is stable enough.

I also feel that battery consuming in MIUI10 and Android System is always No.1 in battery statistics. Have u ever submit these bugs to MIUI, i think that issue may takes a long time for miui to fix them. Maybe for me, the style of notification of MIUI10 and the gesture make me dont want to go back to  MIUI9.

**Comment by linusyang92** [comment]
Close due to inactivity.
