### ISSUE TITLE
Cleaner-fix.sh doesn't support Android P image

### ISSUE THREAD

**Issue by EraserKing** [linusyang92/mipay-extract#16]
Cleaner-fix.sh looks not supporting the new br format of system image
For example, for this image (http://miui.dedyk.gq/8.9.20/xiaomi.eu_multi_MIMix2S_8.9.20_v10-9.zip), which is for MIX 2S / MIUI 10 / Android P, cleaner-fix.sh fails immediately after only extracting the zip file.
In the extracted folder, there's only one file, "system.transfer.list", and no other files.
I searched the file and found there's no call to brotli, like extract.sh, so I think this bash shell is not updated yet.

![image](https://user-images.githubusercontent.com/1160403/45917558-6ac8d880-beac-11e8-8a2e-75c475f3e45e.png)

**Comment by linusyang92** [comment]
@EraserKing Fixed the `brotli` issue in the latest script. The string search performance under Windows/Cygwin is also greatly improved. Find+Grep was painfully slow due to the slow fork implementation of Cygwin. I switched to Windows native `findstr` command instead.

**Comment by EraserKing** [comment]
Thanks. This time it's working well.
I can see lunar calendar in the app.
