### ISSUE TITLE
compact_dex_converter for old cpu's

### ISSUE THREAD

**Issue by bursoft-git** [linusyang92/mipay-extract#20]
Hello linusyang92!
Thanks for precompiled 32-bit compact_dex_converter for usage with flinux!
Сould you compile this binary with a patch for old processors?
https://github.com/anestisb/vdexExtractor/issues/29#issuecomment-425385862
Thanks!

**Comment by bursoft-git** [comment]
by the way, I compiled the latest version of flinux.exe for my utiliy Batch ApkTool
here it is, if needed
[flinux.zip](https://github.com/linusyang92/mipay-extract/files/2434907/flinux.zip)

**Comment by linusyang92** [comment]
@bursoft-git Please check the latest commit.

**Comment by bursoft-git** [comment]
@linusyang92
my tester confirmed that new compact_dex_converter works on old cpu (Core 2 Duo E4300)
thanks!
