### ISSUE TITLE
Ubuntu Windows Subsystem compact_dex_converter_linux error

### ISSUE THREAD

**Issue by michaelmaverick** [linusyang92/mipay-extract#21]
--> rom: MIMIX2S v8.10.11
--> image extracted: miui-MIMIX2S-8.10.11-system.img
--> copying apps
----> copying Mipay...
----> copying NextPay...
----> copying TSMClient...
----> copying UPTsmService...
--> framework arch: arm64
--> vdex detected
--> deodexing Mipay...
[INFO] Processing 1 file(s) from Mipay.vdex
[INFO] 1 out of 1 Vdex files have been processed
[INFO] 1 Dex files have been extracted in total
[INFO] Extracted Dex files are available in '.'
./extract.sh: line 166: /mipay-extract-master/tools/cdex/compact_dex_converter_linux: cannot execute binary file: Exec format error

**Comment by linusyang** [comment]
@michaelmaverick WSL is not going to be supported. Run batch file `extract.bat` instead. See [this post](https://github.com/linusyang92/mipay-extract/issues/17#issuecomment-423891773) for details.
