### ISSUE TITLE
有没有可能在eu版里恢复“短信智能识别”和“骚扰拦截”功能

### ISSUE THREAD

**Issue by huyz-git** [linusyang92/mipay-extract#23]
如果能恢复的话，这两个功能还是有一定用处的。
eu版的短信设置里是有“短信智能识别”这一选项的，不过即使打开这个选项验证码短信还是不会识别。

**Comment by zfk513** [comment]
@huyizheng 拦截骚扰有，但是没有联网
短信识别 忍一忍就好了
