### ISSUE TITLE
How about stable roms

### ISSUE THREAD

**Issue by xuzhenhuicn** [linusyang92/mipay-extract#27]
any support for miui10 stable roms? tks

**Comment by AbelDuan** [comment]
it works on miui10

**Comment by linusyang92** [comment]
@xuzhenhuicn It should work with stable roms. So-called stable roms are just old beta/dev rom. Simply download rom zip file and run the script.

**Comment by xuzhenhuicn** [comment]
i downloaded [xiaomi.eu_multi_MI8_V10.1.2.0.PEACNFI_v10-9.zip](https://sourceforge.net/projects/xiaomi-eu-multilang-miui-roms/files/xiaomi.eu/MIUI-STABLE-RELEASES/MIUIv10/xiaomi.eu_multi_MI8_V10.1.2.0.PEACNFI_v10-9.zip/download) for mi MI8 , ran the cleaner-fix.sh, got eufix-MI8-V10.1.2.0.PEACNFI.zip and installed it after i flashed the eu_miui.zip, but i got a blackscreen when i rebooted system. So i clean flashed eu_miui.zip again without installing eufix zip and things turned to be ok. what can i do for that? tks
@linusyang92

**Comment by linusyang92** [comment]
Paste output of the script. Upload your generated files.

**Comment by xuzhenhuicn** [comment]
--> rom: MI8 vV10.1.2.0.PEACNFI

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel Xeon Processor (Skylake, IBRS) (50654),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1575284627 bytes (1503 MiB)

Extracting archive: ../xiaomi.eu_multi_MI8_V10.1.2.0.PEACNFI_v10-9.zip
--
Path = ../xiaomi.eu_multi_MI8_V10.1.2.0.PEACNFI_v10-9.zip
Type = zip
Physical Size = 1575284627
Comment = signed by SignApk

Everything is Ok

Files: 2
Size:       1150857632
Compressed: 1575284627
sdat2img binary - version: 1.0

Android Nougat 7.x / Oreo 8.x detected!

extracting |################################| 100%
Done! Output image: miuieu-MI8-V10.1.2.0.PEACNFI-system.img
--> image extracted: miuieu-MI8-V10.1.2.0.PEACNFI-system.img
--> copying apps
----> copying CleanMaster...
----> copying Calendar...
----> copying SecurityCenter...
----> copying Weather...
--> decompiling CleanMaster...
 'classes.dex' as 'classes.dex'...
--> decompiling Calendar...
----> patched method: isGreaterChina => false
----> patched method: isMainlandChina => false
----> patched method: showsDayDiff => true
----> patched method: showsLunarDate => true
----> patched method: showsWidgetHoliday => true
----> patched method: showsWorkFreeDay => false
 'classes.dex' as 'classes.dex'...
--> decompiling SecurityCenter...
----> patched smali: SettingsActivity.smali
 'classes.dex' as 'classes.dex'...
--> decompiling Weather...
----> searching smali...
----> patched smali: Statistics.smali
----> patched smali: AMapLocationGetter.smali
----> patched smali: ToolsNet.smali
----> patched smali: ToolUtils.smali
----> patched smali: Speaker.smali
----> patched smali: ActivityDailyForecastDetail.smali
----> patched smali: AQIData.smali
----> patched smali: Spider.smali
----> patched smali: WeatherApplicationDelegate.smali
----> patched smali: LocationUpdater.smali
----> patched smali: CitySession$LocationTask.smali
----> patched smali: ActivityWeatherMain$5.smali
----> patched smali: ActivityWeatherMain.smali
----> patched smali: WeatherPushManager.smali
----> patched smali: CurrentConditions.smali
----> patched smali: VerticalCarousel.smali
----> patched smali: InternationalDetails.smali
----> patched smali: HourlyForecast.smali
----> patched smali: PermissionUtils.smali
----> patched method: canRequestCommercial => false
----> patched method: canRequestCommercialInfo => false
 'classes.dex' as 'classes.dex'...
--> packaging flashable zip
--> done
--> all done

**Comment by xuzhenhuicn** [comment]
[eufix-MI8-V10.1.2.0.PEACNFI.zip](https://drive.google.com/file/d/1I9XI43gEN4rve8DyJYjN0FJv1rvqH75S/view?usp=sharing)
@linusyang92

**Comment by linusyang92** [comment]
The log seems good to me. So the issue may be on the xiaomi.eu's side. Maybe you can try cleaning the dalvik cache.

**Comment by xuzhenhuicn** [comment]
> The log seems good to me. So the issue may be on the xiaomi.eu's side. Maybe you can try cleaning the dalvik cache.

OK tks for answering, maybe i'll try again sometime.

**Comment by linusyang92** [comment]
Close due to inactivity.
