### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by leviguan** [linusyang92/mipay-extract#29]
>extract.bat --appvault: extract.bat --appvault
extract.sh: line 2: $'\r': command not found
extract.sh: line 3: cd: $'.\r': No such file or directory
extract.sh: line 4: $'\r': command not found
extract.sh: line 9: syntax error near unexpected token `$'in\r''
'xtract.sh: line 9: `case $key in

**Comment by linusyang92** [comment]
@leviguan Line-ending issues. Please try to re-download your scripts from https://github.com/linusyang92/mipay-extract/archive/master.zip.
