### ISSUE TITLE
MI8 机型如何提取除了mipay的另外两个呢？

### ISSUE THREAD

**Issue by shawnleetttt** [linusyang92/mipay-extract#30]
“eufix-appvault-MIMIX2-9.1.17” & “eufix-MIMix2-9.1.17” for MI8
And thanks for your mipay tool

**Comment by linusyang92** [comment]
`eufix-*.zip`: Run cleaner-fix.sh/bat
`eufix-appvault-*.zip`: Run extract.sh/bat with argument `--appvault`.
Please read the readme document.
