### ISSUE TITLE
Cannot extract MI8_9.1.24

### ISSUE THREAD

**Issue by hyyz17200** [linusyang92/mipay-extract#31]
The rom version is miui_MI8_9.1.24_5d1a0531c8_9.0.zip

Tried both windows and debian, with the same error log:

![qq 20190205102657](https://user-images.githubusercontent.com/4502808/52250015-dded5b80-2930-11e9-9969-ea6871f8484b.png)

**Comment by linusyang92** [comment]
Please try the latest version again.

**Comment by linusyang92** [comment]
Close due to inactivity.
