### ISSUE TITLE
Any idea to convert this to a magisk module?

### ISSUE THREAD

**Issue by 2ndMessiah** [linusyang92/mipay-extract#35]
It'll be much cleaner that way. Thx.

**Comment by linusyang92** [comment]
Magisk is by no means **cleaner**, which just puts everything in its own folder and mount it at boot. All these steps can be done well using recovery scripts. And this will also introduce anther unnecessary dependency and may cause failure if the Magisk does not play well with MIUI on certain devices. I will not officially support this feature, but you can fork this project and add Magisk support as you like.

**Comment by linusyang92** [comment]
Close due to inactivity.
