### ISSUE TITLE
Changes of 'Calendar' app in recent xiaomi.eu roms

### ISSUE THREAD

**Issue by xsm1997** [linusyang92/mipay-extract#40]
For the recent xiaomi.eu roms, the Calendar app has changed its path from '/system/priv-app/Calendar' to '/system/app/Calendar'. So the present logic in the 'cleaner-fix.sh' would not extract nor patch the Calendar app.
I edited the script, removed 'Calendar' in mipay_apps and added 'app/Calendar' to private_apps. After that, the script runs normally and the Calendar app get patched. (Test on xiaomi.eu RedMi K20Pro 9.7.27) But I don't know whether the way I edited the script is correct or not. So it is the reason why I opened an issue, not a PR.
Hope this will get resolved soon.

**Comment by xsm1997** [comment]
In today's update of xiaomi.eu roms, the path of Calendar app has reverted to '/system/priv-app/Calendar'. So there is no need to patch the script. Closing this issue.

**Comment by QSCFTHMKO** [comment]
There is another change in 'Calendar' app since xiaomi.eu 9.12.19
--> decompiling Calendar...
----> Ignore patch: "LocalizationUtils.smali" not found
and Lunar dates patch is not work.
