### ISSUE TITLE
安卓Q版本的可以用么

### ISSUE THREAD

**Issue by chenchenfang** [linusyang92/mipay-extract#45]
我现在用的是小米8屏幕指纹版 刷的是这个国际版 xiaomi.eu_multi_MI8Pro_9.10.24_v11-10.zip
提取的是V11.0.2.0.PECCNXM （MIUI11）  国内官网的这个版本的 mipay
然后点击小米钱包中的小米公交 不能用 显示重试...点了还是没有用,.,..

**Comment by chenchenfang** [comment]
我又试了试 国内的开发版 提取   然后可以用了

**Comment by chenchenfang** [comment]
当然也可能是 系统时间问题  我第二次修改成了国内的时区  之前不是国内的

**Comment by whyunzheng** [comment]
楼主提取的MIPAY能发一个给我吗
