### ISSUE TITLE
关于时钟提取的问题

### ISSUE THREAD

**Issue by chenchenfang** [linusyang92/mipay-extract#46]
我看这个源码可以直接写app然后提取出来 
所以我就像提取时钟出来 
虽然提取出来了但是 时钟没有工作日闹钟的那个选项
就有点难受....

**Comment by chenchenfang** [comment]
```
case $key in
    --appvault)
    EXTRA_PRIV="priv-app/PersonalAssistant app/MetokNLP $EXTRA_PRIV"
    echo "--> Enabled app vault extract"
    shift
    ;;
    *)
    darr+=("$1")
    shift
    ;;
esac
done

mipay_apps="Mipay NextPay TSMClient UPTsmService DeskClock"
private_apps=""
[ -z "$EXTRA" ] || mipay_apps="$mipay_apps $EXTRA"
[ -z "$EXTRA_PRIV" ] || private_apps="$private_apps $EXTRA_PRIV"
```

**Comment by chenchenfang** [comment]
```sh
case $key in
    --appvault)
    EXTRA_PRIV="priv-app/PersonalAssistant app/MetokNLP $EXTRA_PRIV"
    echo "--> Enabled app vault extract"
    shift
    ;;
    *)
    darr+=("$1")
    shift
    ;;
esac
done
//这里添加了DeskClock
mipay_apps="Mipay NextPay TSMClient UPTsmService DeskClock"
private_apps=""
[ -z "$EXTRA" ] || mipay_apps="$mipay_apps $EXTRA"
[ -z "$EXTRA_PRIV" ] || private_apps="$private_apps $EXTRA_PRIV"
```

**Comment by MonwF** [comment]
不需要单独提取，可以跑`cleaner-fix`的脚本，会生成zip包，刷进去就可以修复这个问题。包含日历显示农历，天气源使用中国天气等 @chenchenfang

**Comment by chenchenfang** [comment]
我已经用回了国内版.. 
不过还是谢谢你 
国外的rom也就用一个 google play验证通过 
还有就是国外的rom没有小爱同学..懒得折腾了 
@MonwF

**Comment by MonwF** [comment]
> 我已经用回了国内版..
> 不过还是谢谢你
> 国外的rom也就用一个 google play验证通过
> 还有就是国外的rom没有小爱同学..懒得折腾了
> @MonwF

小爱同学直接装app就可以了，使用没有任何问题。
安装小米的应用商店后，可以收到系统app的更新，和国内版没区别

**Comment by Zephyr0221** [comment]
> > 我已经用回了国内版..
> > 不过还是谢谢你
> > 国外的rom也就用一个 google play验证通过
> > 还有就是国外的rom没有小爱同学..懒得折腾了
> > @MonwF
> 
> 小爱同学直接装app就可以了，使用没有任何问题。
> 安装小米的应用商店后，可以收到系统app的更新，和国内版没区别

安卓10有效果吗，我刷了好像没效果。还有我刷那个extract.bat --appvault会报错，不知道什么原因

**Comment by xspeed1989** [comment]
> > 我已经用回了国内版..
> > 不过还是谢谢你
> > 国外的rom也就用一个 google play验证通过
> > 还有就是国外的rom没有小爱同学..懒得折腾了
> > @MonwF
> 
> 小爱同学直接装app就可以了，使用没有任何问题。
> 安装小米的应用商店后，可以收到系统app的更新，和国内版没区别
@MonwF 
知道怎么开启小爱的语音唤醒吗？

xiaomi.eu里面的主题商店，主题是国内的，但是字体是国外的
我提取了system/font整个用面具补丁了一下，还是主题商店更方便
还有个就是全球上网是空白的
