### ISSUE TITLE
Hope to support extract apps from system/priv-app

### ISSUE THREAD

**Issue by seanliu96** [linusyang92/mipay-extract#5]
Hi, I notice you have added a new feature to extract EXTRA apps from ROMs. But I find the script only find apps from system/app (line 187 at extract.sh). I want to extract the virtualsim which is located at system/priv-app. However, current version code will clean the work_dir if failing to find any app. Please consider this request.

Thanks.

**Comment by linusyang** [comment]
No plan to support extract apps from other locations. You can modify the script on your own.
