### ISSUE TITLE
Compile new static 32-bit compact_dex_converter with API_29 support

### ISSUE THREAD

**Issue by bursoft-git** [linusyang92/mipay-extract#50]
Can you compile new static 32-bit compact_dex_converter with API_29 support?
**[anestisb](https://github.com/anestisb)** released it yesterday https://github.com/anestisb/vdexExtractor/issues/56
Thanks!

**Comment by linusyang92** [comment]
Please check the latest version.

**Comment by bursoft-git** [comment]
Thank you, it works!
