### ISSUE TITLE
MIUI11_安卓10已成功移植小米公交，在此分享一下

### ISSUE THREAD

**Issue by CodeInDreams** [linusyang92/mipay-extract#51]
年前还找不到，年后很轻松就找到了，相信需要的朋友会来这里找（作者别介意哈打扰了）  
我的机型是**MIX2S**，其他机型自己尝试哈~  
  
[下载链接](https://file.huitools.com/share/DLpU1qF9?dl=1)  
  
![Screenshot_2020-02-25-15-00-00-998_com mipay wallet](https://user-images.githubusercontent.com/17664279/75223492-8773e900-57e1-11ea-9ac6-0efd083a5e86.jpg)
![Screenshot_2020-02-25-15-03-34-982_com miui tsmclient](https://user-images.githubusercontent.com/17664279/75223495-893dac80-57e1-11ea-96a6-b7f8cb763df7.jpg)
![Screenshot_2020-02-25-15-03-56-761_lockscreen](https://user-images.githubusercontent.com/17664279/75223497-89d64300-57e1-11ea-9149-4db62d7d4629.jpg)

**Comment by CheerChen** [comment]
想问下是否有调起门卡闪退的问题?

**Comment by CodeInDreams** [comment]
> 想问下是否有调起门卡闪退的问题?

无

**Comment by TheAutomatic** [comment]
是不是要eu版miui才行，如果我想用pixel expirence呢？

**Comment by CodeInDreams** [comment]
> 是不是要eu版miui才行，如果我想用pixel expirence呢？

@TheAutomatic 当然必须是EU版MIUI才行，EU版是基于国内版修改的，所以这个移植只是让阉割掉的长回来，本身没有的肯定不行的撒

**Comment by fishtorres** [comment]
问下刷的时候.zip无效是怎么回事

**Comment by TheAutomatic** [comment]
> 问下刷的时候.zip无效是怎么回事

楼主发的这个不是刷入用的，要把里面的几个app的文件夹复制到/system_root/system/app（好像是这个路径）下面。
而且应该不是所有机型通用，我K20pro就不行，建议自己提取。

**Comment by fishtorres** [comment]
> > 问下刷的时候.zip无效是怎么回事
> 
> 楼主发的这个不是刷入用的，要把里面的几个app的文件夹复制到/system_root/system/app（好像是这个路径）下面。
> 而且应该不是所有机型通用，我K20pro就不行，建议自己提取。

那我自己试试。。不想root

**Comment by TheAutomatic** [comment]
> > > 问下刷的时候.zip无效是怎么回事
> > 
> > 
> > 楼主发的这个不是刷入用的，要把里面的几个app的文件夹复制到/system_root/system/app（好像是这个路径）下面。
> > 而且应该不是所有机型通用，我K20pro就不行，建议自己提取。
> 
> 那我自己试试。。不想root

不想root的话，直接在recovery里面复制到那个文件夹就行了，我就是那么干的。开机后依然没有被root。

**Comment by fishtorres** [comment]
> > > > 问下刷的时候.zip无效是怎么回事
> > > 
> > > 
> > > 楼主发的这个不是刷入用的，要把里面的几个app的文件夹复制到/system_root/system/app（好像是这个路径）下面。
> > > 而且应该不是所有机型通用，我K20pro就不行，建议自己提取。
> > 
> > 
> > 那我自己试试。。不想root
> 
> 不想root的话，直接在recovery里面复制到那个文件夹就行了，我就是那么干的。开机后依然没有被root。

扔进/system/system/app了但是还是没有。。权限问题？

**Comment by TheAutomatic** [comment]
> > > > > 问下刷的时候.zip无效是怎么回事
> > > > 
> > > > 
> > > > 楼主发的这个不是刷入用的，要把里面的几个app的文件夹复制到/system_root/system/app（好像是这个路径）下面。
> > > > 而且应该不是所有机型通用，我K20pro就不行，建议自己提取。
> > > 
> > > 
> > > 那我自己试试。。不想root
> > 
> > 
> > 不想root的话，直接在recovery里面复制到那个文件夹就行了，我就是那么干的。开机后依然没有被root。
> 
> 扔进/system/system/app了但是还是没有。。权限问题？

四个文件夹都放好的话（和其他系统应用放在一起），开机后，如果你是默认的桌面，应该在某个文件夹里会有一个“小米钱包”。
