### ISSUE TITLE
MIUI10国际版无法安装应用

### ISSUE THREAD

**Issue by CrazyMan1226** [linusyang92/mipay-extract#6]
自行创建最新版钱包或开机安装apk都无法正常安装钱包App

**Comment by linusyang** [comment]
@CrazyMan1226 Just tested working perfectly on my Mix 2, OS version is xiaomi.eu 8.6.14. Mi Pay is extracted from MIUI 10 China ROM 8.6.14 using latest script in this repo (can be found in releases).

**Comment by CrazyMan1226** [comment]
之前用6.4做的包没反应 现在用release最新版已解决

**Comment by derkuci** [comment]
MIUI Global 9.6.1.0 (ODEMIFD) 没法安装 releases 里的 8.6.14 或是 8.5.8 的版本。这个 Global 和 EU 版本的有什么不同的地方吗？

**Comment by derkuci** [comment]
谢谢回复 @linusyang 
主要是水平不行，从来没接触过，学习曲线较陡，就偷懒用现成的了。我争取试试。理论上要找完全一样版本但是中国版的 ROM？有没有通常的下载链接能推荐下？

**Comment by uian2000** [comment]
一般来说大版本一致就行，比如同一期的国际版和国内开发版
