### ISSUE TITLE
运行cleaner_fix.bat失败，未输出eufix

### ISSUE THREAD

**Issue by ZvonimirSun** [linusyang92/mipay-extract#7]
如题，运行cleaner_fix.bat失败，未输出eufix。程序直接就到最后一部结束了，没有任何输出，之前运行extract.bat正常。

**Comment by ZvonimirSun** [comment]
Can you please tell me how to see the log? I just run the cleaner-fix.bat. And it only shows that ```--> all done``` and finished, no change happened.
![image](https://user-images.githubusercontent.com/22871764/42032625-c1abb4c6-7b0c-11e8-945d-ea728428e27f.png)

**Comment by linusyang** [comment]
@ZvonimirSun Update to the latest script in this repo. Put your eu rom in the same directory of the script.

**Comment by ZvonimirSun** [comment]
@linusyang Oh, you mean I need to use the eu rom here, I keep using the chinese rom before.

**Comment by linusyang** [comment]
@ZvonimirSun I have updated the readme. There is instruction on how to use eufix scripts.

**Comment by ZvonimirSun** [comment]
@linusyang there's a problem now, after i flashed the eufix, I can't get into the system and I had to flash back to the old rom. The mipay pack doesn't cause the problem, it must be the eufix's problem. the rom i use is xiaomi.eu_multi_MI6_8.6.20_v10-8.0, maybe it doesn't work for it.

**Comment by linusyang** [comment]
@ZvonimirSun You didn't read the readme carefully. You shouldn't use eufix if your data partition is not encrypted. It will definitely brick your device. It only works with an encrypted data partition.

**Comment by ZvonimirSun** [comment]
@linusyang Thank you. I found that simply deleting the keys doesn't change anything, maybe i need to clear my phone. I will try it later.

**Comment by linusyang** [comment]
@ZvonimirSun I have removed the force encryption in the latest version. There is no worry to use the eufix zip now, no matter your device is encrypted or not. There is a separate package called `eufix-force-fbe-oreo` for force encryption.
