### ISSUE TITLE
关于小米公交

### ISSUE THREAD

**Issue by nange520** [linusyang92/mipay-extract#8]
![default](https://user-images.githubusercontent.com/33044636/43111349-69c7da84-8f23-11e8-96fe-7ea898b4018d.png)
我也刷了你最新的补丁，为什么我的啥还是这样，我也清掉 Dalvik Cache，这个有什么解决方法吗？

**Comment by linusyang** [comment]
@nange520 More information please: your device, rom version, output log, etc. Otherwise, I don't know how to help you.

**Comment by linusyang** [comment]
@nange520 By the way, you should extract the flashable zip by yourself (download MIUI China official rom and run the script). Do not use the zip in releases page unless your device is Mix 2 and has the same version in the package name.

**Comment by linusyang** [comment]
@nange520 May be related to #13. Try to re-authorize the permissions of Mipay app.
