### ISSUE TITLE
Unable to extract from miui_MI6_8.8.2_5b44a92e16_8.0.zip

### ISSUE THREAD

**Issue by DevChache** [linusyang92/mipay-extract#9]
Hi, I've downloaded the latest developer ROM for Mi 6 and tried to execute `extract.sh` in your repository. But it seems to quit with errors:

```plain
--> rom: MI6 v8.8.2

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (906E9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 713572352 bytes (681 MiB)

Extracting archive: ../miui_MI6_8.8.2_5b44a92e16_8.0.zip

ERRORS:
Unexpected end of archive

--
Path = ../miui_MI6_8.8.2_5b44a92e16_8.0.zip
Type = zip
ERRORS:
Unexpected end of archive
Physical Size = 713637888

    

Archives with Errors: 1

Open Errors: 1

--> abort
--> clean system.new.dat
```

Thanks for your hard work!

**Comment by linusyang** [comment]
It seems your zip package is malformed, usually caused by incomplete download. Update to the latest version of mipay-extract. Then try 8.8.9 version of Mi 6:

http://bigota.d.miui.com/8.8.9/miui_MI6_8.8.9_90988291c1_8.0.zip

**Comment by DevChache** [comment]
Thanks!

On Sat, Aug 11, 2018, 11:44 PM linusyang <notifications@github.com<mailto:notifications@github.com>> wrote:

It seems your zip package is malformed, usually caused by incomplete download. Update to the latest version of mipay-extract. Then try 8.8.9 version of Mi 6:

http://bigota.d.miui.com/8.8.9/miui_MI6_8.8.9_90988291c1_8.0.zip<https://nam03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fbigota.d.miui.com%2F8.8.9%2Fmiui_MI6_8.8.9_90988291c1_8.0.zip&data=02%7C01%7C%7C06dde4c8fe9b4cc772c608d5ffa1547c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636695990720740732&sdata=1xPFwSNFZNQi3B1JG5T2b4tpWFIUUlLF8jvhw%2BcuDAU%3D&reserved=0>
